
import { createClient } from '@supabase/supabase-js';

// Initialize Supabase client
// Values should be provided via environment variables
const SUPABASE_URL = process.env.REACT_APP_SUPABASE_URL || process.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.REACT_APP_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || '';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

/*
  REQUIRED DATABASE SETUP (Run this in Supabase SQL Editor):

  create table scores (
    id bigint generated by default as identity primary key,
    user_id text not null,
    mode text not null,
    score integer not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- Optional: Enable Row Level Security (RLS)
  alter table scores enable row level security;
  create policy "Public scores are viewable by everyone" on scores for select using (true);
  create policy "Users can insert their own scores" on scores for insert with check (true); 
*/